### ISSUE TITLE
Misleading sentence on typeclass syntax

### ISSUE THREAD

**Issue by trepidacious** [fommil/fp-scala-mortals#11]
Might just be me, but in the Syntax section, you have:

>  If we define boilerplate on the companion of the typeclass, ...code... it allows the use of context bounds

That would imply to me that the boilerplate is necessary for using context bounds, which I don't think is the case. It becomes clearer just after that, where you use `val N = Numeric[T]` to get at the typeclass instance, but I think combining these two things together might be confusing. Would it be better to introduce the context bounds as sugar for the previous named implicit, then say that this means you need something extra to get at the instance without a name for it, then show the boilerplate?

On a related note, is the boilerplate really worth it just to avoid `implicitly[Numeric[T]]`?

**Comment by trepidacious** [comment]
Oh by the way thanks for recommending the book, I've been finding it very readable and picked up quite a few things :)

**Comment by fommil** [comment]
ok, thanks. I'll think of alternative wording.

**Comment by fommil** [comment]
sample updated, thanks for reporting.
