### ISSUE TITLE
Consider changing the title from "for Mortals" to something else

### ISSUE THREAD

**Issue by hmemcpy** [fommil/fp-scala-mortals#5]
First, big kudos on the effort! I really do believe Scala could benefit from a "missing manual" type of book.

I do, however, want to bring up a point of not calling it "for mortals". I, personally, made the switch to Scala after a lifetime on .NET a little less than a year ago, and have been on a journey to learn Scala "the FP way", instead of using it as "a better Java".

It took me a **long time** to watch and re-watch the same talks (by Runar et al) again and again, until it finally started to make sense. It clicked for me, and suddenly I was able to, retroactively, get an intuitive understanding of why things are done the way they are.

Personally, I wanted to get a better understanding of the **why**, when it came to certain FP concepts used in Scala (and various FP libraries), so I'm currently learning Haskell as well. I understand and appreciate your reluctance of including Haskell examples and terminology in your book, but I do think the background is important, as so much of Scala was directly inspired by Haskell.

The point of this issue is a request - don't call it "for Mortals". It perpetuates this view that separates hardcore FP Haskell people from the rest of "ordinary" developers. I don't think it's the case. I once learned a brilliant term for this - *perplexity* - the inability to deal with or understand something complicated or unaccountable. It only seems complicated because we don't (yet) understand it, not because it's inherently hard. So perhaps you could call it "FP in Scala for the Perplexed" :)

Anyway, best of luck to you, and I'm looking forward to reading the result!

**Comment by fommil** [comment]
Thanks for your thoughts. My talk on Shapeless was branded "Shapeless for Mortals" and this is a theme I'd like to continue.
