### ISSUE TITLE
Introduction has a very abrupt ending

### ISSUE THREAD

**Issue by soc** [fommil/fp-scala-mortals#7]
(based on our earlier discussion)

The introduction uses an example to show why abstraction matters and presents a progression of increasingly elaborate approaches:

1. Untyped collections
2. Untyped collections wrapped in domain objects
3. Typed collections with Generics
4. Mixing operations and their execution

While the fourth stage is used to introduce higher-kinded types, the question of "how to move on from this stage" is not answered. The fourth stage is very similar to the second stage (which is a good explanation of how people handled typesafe operations on collections before generic collections shows up) but lacks the conclusion: a fifth step that addresses the issues of the fourth step, just like the third step addressed the issues of the second step.

I think the introduction is very good in showing the motivation for looking at higher-kinded types, but I feel the example given really begs for a conclusion, too.

**Comment by fommil** [comment]
cool, thanks for writing this up. I'll have a think about it, but I'm quite happy with where the Intro ends so I don't believe I will make any major changes. The intro is not meant as a replacement for the entire book.

FYI the kind of feedback that is the most important to me at this stage is of the form "I did not understand X".
